// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izxtyzohydswpfjetwsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6eHR5em9oeWRzd3BmamV0d3NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NDM4NTMsImV4cCI6MjA3MzMxOTg1M30.eCHiE9g1ZNOVNf6I5L0RqdzQViWKayGN8ANeR2pS8NE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});